In [5]:
import numpy as np

In [7]:
data1 = [[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
#начнем работу с массивом
arr1 = np.array(data1)
arr1

array([[5.2, 3. , 4.5],
       [9.1, 0.1, 0.3]])

In [11]:
#количество измерений
arr1.ndim

2

In [13]:
#размер массива
arr1.size

6

In [15]:
#форма массива
arr1.shape

(2, 3)

In [19]:
arr1.dtype

dtype('float64')

In [33]:
#количество элементов массива
arr1.itemsize

8

## Методы библиотеки Numpy

In [27]:
#метод создает массив, состоящий из n количества нулей
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
#создает массив, состоящий из единиц
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [35]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
#метод, позволяющий создать массив от arg1 до arg2, включив в него arg3 аргумента
np.linspace(1, 5, 9)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [51]:
# создание единичной матрицы
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Операции между массивами и скалярами

In [60]:
arr2 = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0,]])

In [62]:
arr2*arr2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [64]:
arr2-arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [68]:
1/arr2

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

## Случайные массивы

In [71]:
np.random.randn(3, 2)

array([[ 1.36990946,  1.05373365],
       [ 1.17312396, -1.17859004],
       [-0.35843836, -1.14562057]])

In [73]:
np.random.randint(1, 1000, 4)

array([175, 626, 828, 484])

## Индексирование 

In [76]:
np.arange(15)[8:12]

array([ 8,  9, 10, 11])

In [84]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [86]:
arr2d[0, 1]

2

In [88]:
arr2d[0][1]

2

### Булевое индексирование

In [92]:
names = np.array(['Bob', 'Mary', 'Den', 'Bob'])
names == 'Bob'

array([ True, False, False,  True])

In [94]:
mask = (names == 'Bob') | (names == 'Mary')
mask

array([ True,  True, False,  True])

In [96]:
names[mask]

array(['Bob', 'Mary', 'Bob'], dtype='<U4')

## Транспонирование массивов

In [110]:
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [104]:
arr2.shape

(2, 3)

In [106]:
arr2.T.shape

(3, 2)

In [108]:
arr2.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

## Математические и статистические операции

In [119]:
arr = np.random.randn(5, 4)
arr

array([[ 0.47321571,  0.20432917,  0.27632659,  1.32652852],
       [-1.00016652, -0.03583416, -1.86344745, -1.36122076],
       [-1.04080214, -1.02585115,  1.33168874, -0.70308814],
       [-1.74899585, -1.16552318,  0.2681268 , -0.56546183],
       [-0.68349947,  1.35250689, -1.12484043, -1.13804402]])

In [121]:
arr.shape

(5, 4)

In [125]:
# среднее значение
arr.mean()

-0.41120263354819536

In [127]:
# сумма элементов на заданной оси, то есть по строкам
arr.sum(axis = 0)

array([-4.00024825, -0.67037242, -1.11214576, -2.44128624])

## Сортировка

In [130]:
arr = np.random.randn(8)
arr

array([ 1.22302408, -0.51627746,  0.3745496 , -2.83245914, -0.58146127,
        0.5808545 ,  0.00975949,  0.9707919 ])

In [138]:
arr.sort()
arr

array([-2.83245914, -0.58146127, -0.51627746,  0.00975949,  0.3745496 ,
        0.5808545 ,  0.9707919 ,  1.22302408])

In [166]:
arr = np.random.randn(5, 3)
arr

array([[-0.52773673, -1.04492317, -1.34129086],
       [-1.49529307,  0.03296084,  0.02690559],
       [ 0.31311775, -1.00108019,  0.56014021],
       [ 0.73780067, -0.38735036,  0.61740197],
       [-0.35100869, -0.30060843,  0.32004949]])

In [164]:
#сортировка с учетом строк
arr.sort(0)
arr

array([[-1.05516824, -0.97166061, -0.57759379],
       [-0.65981052, -0.9279991 , -0.31056646],
       [-0.28434258,  0.37982282,  0.17657016],
       [ 0.46255043,  0.7953953 ,  0.52449735],
       [ 0.85196252,  1.70282303,  0.696328  ]])

In [168]:
#сортировка с учетом столбцов
arr.sort(1)
arr

array([[-1.34129086, -1.04492317, -0.52773673],
       [-1.49529307,  0.02690559,  0.03296084],
       [-1.00108019,  0.31311775,  0.56014021],
       [-0.38735036,  0.61740197,  0.73780067],
       [-0.35100869, -0.30060843,  0.32004949]])

## Сохрание массивов на диске в двоичном формате

In [171]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
np.save('some_array', arr)

In [183]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [185]:
# Сохраним несколько массивов в zip архиве
np.savez('some_array.npz', a = arr, b = arr)

In [187]:
arr_ = np.load('some_array.npz')
arr_['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Задание

Создайте вектор NumPy, который содержит значение от 10 до 500. Возведите все значения вектора в квадрат и вычтите из каждого элементавектора число 234. Чему равна сумма всех элементов, получившегося вектора?

In [201]:
vector = np.arange(10, 501)
new_vector = pow(vector, 2) - 243
new_vector.sum()

41672152